version: "3.8"

services:
  guardian:
    build:
      context: .
      secrets:
        - pip.conf
    depends_on:
      - dynamodb
      - redis
    environment:
      AUTHENTICATION_ENABLED: 0
      ENABLE_RELOAD: 1
      ENABLE_PRETTY_JSON_LOGS: 1
      LOG_LEVEL: "debug"
      AWS_ACCESS_KEY_ID: "super-secret"
      AWS_SECRET_ACCESS_KEY: "super-super-secret" # pragma: allowlist secret
      REGION: "eu-west-1"
    networks:
      - internal
    ports:
      - "8080:8080"

  dynamodb:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   networks:
    - internal
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal

  redis:
    image: redis:7.0-alpine
    networks:
      - internal
    volumes:
      - "./docker/redis:/data"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -c PING | grep -q PONG"]
      interval: 5s
      timeout: 1s
      retries: 10

networks:
  internal:

secrets:
  pip.conf:
    file: ./pip.conf
